### ISSUE TITLE
MYB balance check 

### ISSUE THREAD

**Issue by 0xdewy** [uivlis/token-to-mybit-converter#1]
This balance check should probably check the balance right before the transaction call to bancor and then check it after, as the balance before the call may be greater than 0. 

  require (myBit.balanceOf(this) == convertedValue, "Transaction failed with different return than expected");

**Comment by uivlis** [comment]
```
require (myBit.balanceOf(this) == 0, "Residual MyBit tokens found.");
uint convertedValue = bancorNetwork.convert.value(value)(
    ...
);
require (myBit.balanceOf(this) == convertedValue, "Transaction failed with different return than expected.");
```
Is this your intended correction?

**Comment by 0xdewy** [comment]
I wouldn't restrict it that way because someone could break the contract by transferring in MYB. Maybe just check that `balanceAfter` ==  `convertedValue` +` balanceBefore`

**Comment by uivlis** [comment]
How about now?
```
uint myBitBalanceBefore = myBit.balanceOf(this); 
uint convertedValue = bancorNetwork.convert.value(value)(
    ...
);
require(myBit.balanceOf(this) == myBitBalanceBefore + convertedValue, "Transaction failed with return loss.");
```

**Comment by 0xdewy** [comment]
@uivlis  yes that is the type of check I was reffering to.
